server:
  port: 8080 # 鏈嶅姟绔彛鍙?
  servlet:
    context-path: /api # 娣诲姞鍏ㄥ眬鎺ュ彛鍓嶇紑

spring:
  # 鏁版嵁搴撻厤缃俊鎭?
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_ich?serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: "050501"
    # 杩炴帴姹?
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      auto-commit: true
  # 鏂囦欢涓婁紶閰嶇疆
  servlet:
    multipart:
      max-file-size: 55MB
      max-request-size: 55MB
  # 閰嶇疆swagger
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

sa-token:
  token-name: satoken
  timeout: 86400
  active-timeout: 86400
  is-concurrent: true
  is-share: false
  jwt-secret-key: advasudgqhkdknsakisd
  is-log: true

